// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoveringType } from "./CoveringType";
import type { UncoveringStrategy } from "./UncoveringStrategy";

export type RevealSettings = { image_source: string | null, covering_type: CoveringType, uncovering_strategy: UncoveringStrategy, show_control_buttons: boolean, };
