// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevealSettings } from "./RevealSettings";

export type RevealObject = { image: string, covering: string, question: string | null, answers: Array<string>, correct_answer: number, settings: RevealSettings, };
